# Generated by Django 3.0.5 on 2020-05-01 21:56

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import django_mysql.models.fields.lists
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year_of_publication', models.DateField(blank=True, null=True)),
                ('ISBN', models.CharField(help_text='13 Character ISBN number', max_length=13, null=True, verbose_name='ISBN')),
                ('status', models.BooleanField(choices=[('A', 'Available'), ('R', 'Reserved')], default='A', help_text='Book Status', max_length=1)),
                ('reviews', django_mysql.models.ListTextField(models.CharField(max_length=200), help_text='Give a review of the book', size=10)),
                ('author', models.ManyToManyField(to='online_library.Author')),
            ],
            bases=(models.Model, django_mysql.models.fields.lists.ListTextField),
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('M', 'Maintenance'), ('O', 'On loan'), ('A', 'Available'), ('R', 'Reserved')], default='m', help_text='Book availability', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_library.Book')),
            ],
            options={
                'ordering': ['book'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_library.Publisher'),
        ),
    ]
