# Generated by Django 3.0.5 on 2020-05-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
