# Generated by Django 3.0.5 on 2020-05-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_library', '0003_auto_20200504_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.CharField(default='N/A', editable=False, help_text='After your account has been created, it can never be edited.', max_length=8, primary_key=True, serialize=False, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
