# Generated by Django 3.0.5 on 2020-05-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_library', '0006_auto_20200505_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(default='N/A', editable=False, help_text='After your account has been created, it can never be edited.', max_length=8),
        ),
    ]
