# Generated by Django 3.0.5 on 2020-05-21 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_borrowedbefore_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbefore',
            name='book_instance',
        ),
        migrations.RemoveField(
            model_name='borrowedbefore',
            name='date',
        ),
        migrations.AddField(
            model_name='borrowedbefore',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Book'),
        ),
    ]
